### ISSUE TITLE
Should be ported to lablgtk3

### ISSUE THREAD

**Issue by glondu** [zoggy/lablgtk-extras#1]
gtksourceview2 is no longer maintained upstream, lablgtk-extras should be ported to lablgtk3 which has gtksourceview3 bindings.

**Comment by zoggy** [comment]
A release 3.0 is coming soon (package has been submitted to opam repository).
By the way, the development has moved to https://framagit.org/zoggy/lablgtk-extras/

**Comment by glondu** [comment]
What is the status of this?

The latest version in opam repository is 1.6: https://opam.ocaml.org/packages/lablgtk-extras/

**Comment by zoggy** [comment]
=> https://opam.ocaml.org/packages/lablgtk3-extras/
